[package]
name = "dff"
version = "0.1.0"
authors = ["Suresh Sundriyal"]
description = "A simple duplicate file finder."
license = "BSD 2-clause"

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
